spring:
  application:
    name: learn-microservices-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
learn-microservices-service:
 greeting: "Ol√°"
 default-value: "Mundo"

